### ISSUE TITLE
missing import in app.component.ts ??

### ISSUE THREAD

**Issue by Patleod** [firehist/angular2-courses#1]
:bug: should we add in app.component.ts:

```javascript
import { ProductModule } from './products/product.module';
import { ProductService } from './products/product.service';
```

is that correct ??

**Comment by firehist** [comment]
Dunno about which `app.component.ts` are you talking about!

**Comment by Patleod** [comment]
sorry,  angular2-courses/Ressources/Challenges/12_Angular Modules/app/app.component.ts

**Comment by firehist** [comment]
Hey, I don't think so.
We imported `ProductModule` into the `app.module.ts` (not `app.component.ts`)
https://github.com/firehist/angular2-courses/blob/master/Ressources/Challenges/12_Angular%20Modules/app/app.module.ts#L8
https://github.com/firehist/angular2-courses/blob/master/Ressources/Challenges/12_Angular%20Modules/app/app.module.ts#L19

What about the `ProductService` is that it is already provided into the `ProductModule`:
https://github.com/firehist/angular2-courses/blob/master/Ressources/Challenges/12_Angular%20Modules/app/products/product.module.ts#L8

**Comment by Patleod** [comment]
Sorry again, everything is correct in here. Cant reproduce the error, the problème was certainly on my local clone only !!! :confused:

**Comment by firehist** [comment]
Don't be sorry for that :)
Good luck.
